EGPT/EGPT/main/routes.py
from flask import render_template, request, jsonify, Blueprint, flash, redirect, url_for, abort, session
from flask_login import login_required, current_user
from EGPT.models import Dictionary, User, Messages, Tutorial, UserProgress, Service
from EGPT.main.forms import DeleteForm, ContactForm
from EGPT import db
import datetime
from EGPT.main.utils import DictionaryClass
from new.chat import get_response

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template('index.html')

@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route("/contact_us", methods=['GET', 'POST'])
@login_required
def contact_us():
    form = ContactForm()
    if form.validate_on_submit():
        contact = Messages(user_id=current_user.id, subject=form.subject.data, message=form.message.data)
        db.session.add(contact)
        db.session.commit()
        flash('Your message has been sent!', 'success')
        return redirect(url_for('main.home'))
    return render_template('contact.html', title='Contact Us', form=form)

@main.route("/dictionary/<int:word_id>")
def meaning(word_id):
    word_entry = Dictionary.query.get_or_404(word_id)
    meaning = DictionaryClass().get_definition(word_entry.word)
    return render_template('meaning.html', title=word_entry.word, meaning=meaning)

@main.route('/dictionary')
def dictionary():
    words = Dictionary.query.all()
    form = DeleteForm()
    return render_template('dictionary.html', words=words, form=form)


@main.route('/learning', methods=['GET'])
def learning():
    services = Service.query.all()
    service_list = []
    for service in services:
        # Calculate user progress for each service
        total_tutorials = len(service.tutorials)
        if current_user.is_authenticated:
            viewed_tutorials = UserProgress.query.filter_by(user_id=current_user.id, is_viewed=True).filter(UserProgress.tutorial_id.in_([t.id for t in service.tutorials])).count()
            progress = (viewed_tutorials / total_tutorials) * 100 if total_tutorials > 0 else 0
        else:
            progress = 0
        
        service_list.append({
            'name': service.name,
            'description': service.description,
            'progress': progress
        })
    return render_template('learning.html', services=service_list)

@main.route('/service/<service_name>')
def service_detail(service_name):
    service = Service.query.filter_by(name=service_name.replace('_', ' ')).first_or_404()

    tutorials = Tutorial.query.filter_by(service_id=service.id).all()
    tutorial_list = []
    for tutorial in tutorials:
        viewed = UserProgress.query.filter_by(user_id=current_user.id, tutorial_id=tutorial.id, is_viewed=True).first()
        tutorial_list.append({
            'id': tutorial.id,
            'title': tutorial.title,
            'video_url': tutorial.video_url,
            'viewed': bool(viewed)
        })

    return render_template('service_detail.html', service={'name': service.name}, tutorials=tutorial_list)

# Route to mark a tutorial as viewed
@main.route('/mark_tutorial_viewed/<int:tutorial_id>', methods=['POST'])
@login_required
def mark_tutorial_viewed(tutorial_id):
    tutorial = Tutorial.query.get_or_404(tutorial_id)
    progress = UserProgress.query.filter_by(user_id=current_user.id, tutorial_id=tutorial.id).first()
    
    if not progress:
        # If no record exists, create one
        progress = UserProgress(user_id=current_user.id, tutorial_id=tutorial.id, is_viewed=True, completion_date=datetime.datetime.utcnow())
        db.session.add(progress)
    else:
        progress.is_viewed = True
        progress.completion_date = datetime.datetime.utcnow()
    
    db.session.commit()
    
    # Optionally return the updated progress percentage
    return jsonify({'message': 'Tutorial marked as viewed successfully'}), 200

@main.post("/chat") 
def chat():
    try:
        text = request.json['message']
        response = get_response(text)
        message = {"answer": response}
        return jsonify(message)
    except Exception as e:
        print(f"Error: {e}")
        return jsonify({"answer": "Something went wrong"}), 500
    

@main.route("/admin/messages")
@login_required
def messages():
    page = request.args.get('page', 1, type=int)  # Get the current page from the query string (default is 1)
    messages = Messages.query.paginate(page=page, per_page=3)  # Paginate with 3 messages per page
    
    if current_user.is_admin:
        return render_template('admin.html', messages=messages)
    else:
        abort(403)

@main.route("/delete_message/<int:message_id>", methods=['POST'])
@login_required
def delete_message(message_id):
    message = Messages.query.get_or_404(message_id)
    db.session.delete(message)
    db.session.commit()
    flash('Message has been deleted!', 'success')
    return redirect(url_for('main.admin_messages'))

EGPT/EGPT/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from EGPT import db, bcrypt
from EGPT.models import User, Messages, UserProgress
from EGPT.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from EGPT.users.utils import save_picture, send_reset_email
from flask import Blueprint

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(first_name=form.first_name.data, last_name=form.last_name.data, username=form.username.data, 
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


# Route for user account page
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        changes_made = False

        # Handle profile picture update
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
            changes_made = True

        # Handle username update
        if current_user.username != form.username.data:
            current_user.username = form.username.data
            changes_made = True

        # Handle email update
        if current_user.email != form.email.data:
            current_user.email = form.email.data
            changes_made = True

        # Commit changes to the database
        if changes_made:
            db.session.commit()
            flash('Your account has been updated!', 'success')
        else:
            flash('No changes were made.', 'info')

        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    total_emails = Messages.query.count()
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form, total_emails=total_emails)

@users.route("/delete_account", methods=['POST'])
@login_required
def delete_account():
    user = current_user
    Messages.query.filter_by(user_id=user.id).delete()
    UserProgress.query.filter_by(user_id=user.id).delete()
    db.session.delete(user)
    db.session.commit()
    flash('Your account has been deleted.', 'success')
    return redirect(url_for('main.home'))

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

EGPT/EGPT/templates/about.html
{% extends 'layout.html' %}

{% block content %}

<section id="about-me" class="about-me section">
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <!-- About Content -->
            <div class="col-lg-10" data-aos="fade-up">
                <div class="about-me-info text-center">
                    <h2 class="mb-4">Samuel Ephrem</h2>
                    <p class="subtitle mb-3">Full-Stack Developer & AI Enthusiast</p>
                    <div class="mb-4">
                        <a href="{{url_for('main.contact_us')}}" class="btn btn-primary custom-btn px-4 py-2 shadow-sm">Let's Connect</a>
                    </div>
                    <p class="about-text">
                        I am a recent Computer Science graduate and a full-stack developer with a passion for creating innovative web applications and integrating AI to enhance user experiences. I specialize in building tailored websites that combine modern designs with functionality.
                    </p>
                    <p class="about-text">
                        My expertise spans both frontend and backend development, with a strong interest in AI-driven solutions. I aim to make websites smarter and more adaptive, ensuring they meet the unique needs of each user.
                    </p>
                    <ul class="key-skills mt-4 text-left">
                        <li><i class="bi bi-star-fill"></i><strong> Key Skills:</strong> Full-Stack Development, AI Integration, UX/UI Design</li>
                        <li><i class="bi bi-star-fill"></i><strong> Technologies:</strong> Python, JavaScript, Flask, React, SQL, PyTorch</li>
                        <li><i class="bi bi-star-fill"></i><strong> Projects:</strong> Amharic text to Ethiopian sign language translator, Home appliance selling website and more...</li>
                    </ul>
                </div>
                <div class="social-links text-center mt-4">
                    <a href="https://linkedin.com/in/sam-eph" class="btn btn-outline-primary m-1 social-btn"><i class="fab fa-linkedin"></i> LinkedIn</a>
                    <a href="https://github.com/sameph" class="btn btn-outline-dark m-1 social-btn"><i class="fab fa-github"></i> GitHub</a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

EGPT/EGPT/templates/account.html
{% extends 'layout.html' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/account.css') }}" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<main>
  <div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
    <div class="row">
      <div class="col-md-4">
        <div class="profile-picture">
          <img id="profileImg" src="{{ image_file }}" alt="Profile Picture">
          {{ form.picture(id="profilePicInput", class="profile-form-control-file") }}
          {% if form.picture.errors %}
            {% for error in form.picture.errors %}
              <span class="text-danger" style="position: relative; top: 15px;">{{ error }}</span><br>
            {% endfor %}
          {% endif %}
        </div>
      </div>
      <div class="col-md-8">
        <div class="profile-details">
          <h1>Account Settings</h1>
            {{ form.hidden_tag() }}
            <div class="input-group">
              {{ form.username.label(class="profile-form-label") }}
              {% if form.username.errors %}
                {{ form.username(class="profile-form-control is-invalid") }}
                <div class="profile-invalid-feedback invalid-feedback">
                  {% for error in form.username.errors %}
                    <span class="text-danger">{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.username(class="profile-form-control") }}
              {% endif %}
            </div>
            <div class="input-group">
              {{ form.email.label(class="profile-form-label") }}
              {% if form.email.errors %}
                {{ form.email(class="profile-form-control is-invalid") }}
                <div class="profile-invalid-feedback invalid-feedback">
                  {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.email(class="profile-form-control") }}
              {% endif %}
            </div>
            <div class="input-group">
              {{ form.submit(class="profile-btn") }}
            </div>
          </form>
          <div class="delete-account">
            <h2>Delete Account</h2>
            <p>Are you sure you want to delete your account? This action is irreversible.</p>
            <form method="POST" action="{{ url_for('users.delete_account') }}">
              {{ form.hidden_tag() }}
              <button type="submit" class="delete-btn">Delete Account</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

EGPT/EGPT/templates/admin.html
{% extends 'layout.html' %}

{% block title %}Messages{% endblock %}

{% block content %}
<section class="messages">
    <h2>Messages</h2>
    <div class="message-list">
      {% for message in messages.items %}  <!-- Use .items to access paginated messages -->
        <div class="message-item">
            <div class="message-header">
                <h3>Subject: {{ message.subject }}</h3>
                <span class="timestamp">{{ message.timestamp.strftime('%Y-%m-%d %H:%M') }}</span>
            </div>
            <p class="message-content">{{ message.message }}</p>
            <div class="message-footer">
                <span class="user-id">User ID: {{ message.user_id }}</span>
                <form action="{{ url_for('main.delete_message', message_id=message.id) }}" method="post">
                    <button type="submit" class="delete-btn"><i class="fas fa-trash-alt"></i> Delete</button>
                </form>
            </div>
        </div>
      {% endfor %}
    </div>
  
    <!-- Pagination controls -->
    <div class="pagination">
      {% if messages.has_prev %}
        <a href="{{ url_for('main.messages', page=messages.prev_num) }}" class="prev-btn">Previous</a>
      {% endif %}
      
      {% if messages.has_next %}
        <a href="{{ url_for('main.messages', page=messages.next_num) }}" class="next-btn">Next</a>
      {% endif %}
    </div>
  </section>
  
{% endblock content %}

EGPT/EGPT/templates/contact.html
{% extends 'layout.html' %}

{% block title %}Contact{% endblock %}

{% block content %}

<!-- Contact Section -->
<section id="contact" class="contact section">

  <!-- Section Title -->
  <div class="container section-title" data-aos="fade-up">
    <h2>Contact</h2>
    <div><span>Need Help?</span> <span class="description-title">Contact Us</span></div>
  </div><!-- End Section Title -->

  <div class="container" data-aos="fade" data-aos-delay="100">

    <div class="row gy-4">

      <div class="col-lg-4">
        <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="200">
          <i class="bi bi-geo-alt flex-shrink-0"></i>
          <div>
            <h3>Address</h3>
            <p>NSL, Addis Ababa, Ethiopia</p>
          </div>
        </div><!-- End Info Item -->

        <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="300">
          <i class="bi bi-telephone flex-shrink-0"></i>
          <div>
            <h3>Call Us</h3>
            <p>+251 983 094 987</p>
          </div>
        </div><!-- End Info Item -->

        <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="400">
          <i class="bi bi-envelope flex-shrink-0"></i>
          <div>
            <h3>Email Us</h3>
            <p>samuelephrem07@gmail.com</p>
          </div>
        </div><!-- End Info Item -->

      </div>

      <div class="col-lg-8">
        <form action="{{ url_for('main.contact_us') }}" method="post" data-aos="fade-up" data-aos-delay="200">
          {{ form.hidden_tag() }}
          <div class="row gy-4">

            <div class="col-md-6">
              {{ form.name(class="form-control", placeholder="Your Name", required="") }}
            </div>

            <div class="col-md-6 ">
              {{ form.email(class="form-control", placeholder="Your Email", required="") }}
            </div>

            <div class="col-md-12">
              {{ form.subject(class="form-control", placeholder="Subject", required="") }}
            </div>

            <div class="col-md-12">
              {{ form.message(class="form-control", rows="6", placeholder="Message", required="") }}
            </div>

            <div class="col-md-12 text-center">
              {{ form.submit(class="btn btn-primary") }}
            </div>

          </div>
        </form>
      </div><!-- End Contact Form -->

    </div>

  </div>

</section><!-- /Contact Section -->


</main>

{% endblock content %}

EGPT/EGPT/templates/dictionary.html
{% extends 'layout.html' %}

{% block content %}
<link href="{{url_for('static', filename='css/dictionary.css')}}" rel="stylesheet">
<script src="{{url_for('static', filename='js/dictionary.js')}}"></script>

<div class="dict_container" style="margin-top: 100px;">
    <h1>Dictionary</h1>
    <input type="text" id="searchBox" onkeyup="searchWords()" placeholder="Search for words..." aria-label="Search words">
    <ul id="wordList">
        {% for word in words %}
            <li>
                <a href="{{ url_for('main.meaning', word_id=word.id) }}">{{ word.word }}</a>
            </li>
        {% endfor %}
    </ul>
</div>

<!-- Section to load the meaning -->
<div id="definition" class="definition">
    <!-- The content of the meaning.html will be dynamically loaded here if using AJAX -->
</div>
{% endblock content %}

EGPT/EGPT/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  {% if title %}
    <title>EGPT-{{ title }}</title>
  {% else: %}
    <title>Chatbot Powered Language Learning Platform</title>
  {% endif %}
  <meta name="description" content="">
  <meta name="keywords" content="">

  <!-- Favicons -->
  <link href="img/favicon.png" rel="icon">
  <link href="img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='vendor/aos/aos.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='vendor/glightbox/css/glightbox.min.css')}}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{{url_for('static', filename='css/main.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='css/chatbot.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='css/about.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='css/contact.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='css/messages.css')}}" rel="stylesheet">
  {%block styles %}
  {%endblock styles%}

</head>

<body class="index-page">

  <header id="header" class="header d-flex align-items-center sticky-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

      <a href="{{url_for('main.home')}}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <img src="{{url_for('static', filename='img/egpt.png')}}" alt="">
        <!-- <h1 class="sitename">EGPT</h1> -->
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="{{url_for('main.home')}}" class="active">Home</a></li>
          <li><a href="{{url_for('main.about')}}">About</a></li>
          {% if current_user.is_authenticated %}
            <li><a href="{{url_for('main.learning')}}">Learning</a></li>
          {%endif %}
          <li><a href="{{url_for('main.dictionary')}}">Dictionary</a></li>
          <li><a href="{{url_for('main.contact_us')}}">Contact</a></li>
          {% if current_user.is_authenticated %}
          <li class="dropdown"><a href="#"><span> {{current_user.username}}</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
              <li><a href="{{url_for('users.logout')}}">logout</a></li>
              {% if current_user.is_admin %}
                <li><a href="{{url_for('main.messages')}}">Messages</a></li>
              {%endif%}
              <li class="dropdown"><a href="#"><span>Learning</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                <ul>
                  <li><a href="{{ url_for('main.service_detail', service_name='Vocabulary Mastery'.replace(' ', '_'))}}">Vocabulary Mastery</a></li>
                  <li><a href="{{ url_for('main.service_detail', service_name='Grammar Essentials'.replace(' ', '_'))}}">Grammar Essentials</a></li>
                  <li><a href="{{ url_for('main.service_detail', service_name='Speaking Fluency'.replace(' ', '_'))}}">Speaking Fluency</a></li>
                  <li><a href="{{ url_for('main.service_detail', service_name='Listening Skills'.replace(' ', '_'))}}">Listening Skills</a></li>
                  <li><a href="{{ url_for('main.service_detail', service_name='Writing Proficiency'.replace(' ', '_'))}}">Writing Proficiency</a></li>
                  <li><a href="{{ url_for('main.service_detail', service_name='Reading Comprehension'.replace(' ', '_'))}}">Reading Comprehension</a></li>
                </ul>
              </li>
              <li><a href="{{url_for('users.account')}}">My profile</a></li>
              
            </ul>
          </li>
          {%else:%}
            <li><a href="{{ url_for('users.register') }}">Login/SignUp</a></li>
          {%endif%}

        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

    </div>
  </header>
  <main>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <small class="alert alert-{{ category }}" style="top: 100px;">
            {{ message }}
          </small>
        {% endfor %}
      {% endif %}
    {% endwith %}

 {% block content %}{% endblock %}
 <div class="chatbox">
  <div class="chatbox__support">
      <div class="chatbox__header">
          <div class="chatbox__image--header">
              <img src="https://img.icons8.com/color/48/000000/circled-user-female-skin-type-5--v1.png" alt="image">
          </div>
          <div class="chatbox__content--header">
              <h4 class="chatbox__heading--header">Chat support</h4>
              <p class="chatbox__description--header">Hi. My name is Sam. How can I help you?</p>
          </div>
      </div>
      <div class="chatbox__messages">
          <div></div>
      </div>
      <div class="chatbox__footer">
          <input type="text" placeholder="Write a message...">
          <button class="chatbox__send--footer send__button">Send</button>
      </div>
  </div>
  <div class="chatbox__button">
      <button><img src="{{ url_for('static', filename='img/chatbox-icon.svg') }}" /></button>
  </div>
</div>

<!-- Scroll Top -->
<a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- Preloader -->
<div id="preloader"></div>

<!-- Vendor JS Files -->
<script src="{{url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<script src="{{url_for('static', filename='vendor/php-email-form/validate.js')}}"></script>
<script src="{{url_for('static', filename='vendor/aos/aos.js')}}"></script>
<script src="{{url_for('static', filename='vendor/glightbox/js/glightbox.min.js')}}"></script>

<!-- Main JS File -->
<script src="{{url_for('static', filename='js/main.js')}}"></script>
</main>

<script>
  class Chatbox {
    constructor() {
        this.args = {
            openButton: document.querySelector('.chatbox__button'),
            chatBox: document.querySelector('.chatbox__support'),
            sendButton: document.querySelector('.send__button')
        }

        this.state = false;
        this.messages = [];
    }

    display() {
        const {openButton, chatBox, sendButton} = this.args;

        openButton.addEventListener('click', () => this.toggleState(chatBox))

        sendButton.addEventListener('click', () => this.onSendButton(chatBox))

        const node = chatBox.querySelector('input');
        node.addEventListener("keyup", ({key}) => {
            if (key === "Enter") {
                this.onSendButton(chatBox)
            }
        })
    }

    toggleState(chatbox) {
        this.state = !this.state;

        // show or hides the box
        if(this.state) {
            chatbox.classList.add('chatbox--active')
        } else {
            chatbox.classList.remove('chatbox--active')
        }
    }

    onSendButton(chatbox) {
        var textField = chatbox.querySelector('input');
        let text1 = textField.value
        if (text1 === "") {
            return;
        }

        let msg1 = { name: "User", message: text1 }
        this.messages.push(msg1);

        fetch('http://127.0.0.1:5000/chat', {
            method: 'POST',
            body: JSON.stringify({ message: text1 }),
            mode: 'cors',
            headers: {
              'Content-Type': 'application/json'
            },
          })
          .then(r => r.json())
          .then(r => {
            let msg2 = { name: "Sam", message: r.answer };
            this.messages.push(msg2);
            this.updateChatText(chatbox)
            textField.value = ''

        }).catch((error) => {
            console.error('Error:', error);
            this.updateChatText(chatbox)
            textField.value = ''
          });
    }

    updateChatText(chatbox) {
        var html = '';
        this.messages.slice().reverse().forEach(function(item, index) {
            if (item.name === "Sam")
            {
                html += '<div class="messages__item messages__item--visitor">' + item.message + '</div>'
            }
            else
            {
                html += '<div class="messages__item messages__item--operator">' + item.message + '</div>'
            }
          });

        const chatmessage = chatbox.querySelector('.chatbox__messages');
        chatmessage.innerHTML = html;
    }
}


const chatbox = new Chatbox();
chatbox.display();
</script>


</body>

</html>

EGPT/EGPT/templates/learning.html
{% extends 'layout.html' %}

{% block content %}
<link href="{{url_for('static', filename='css/services.css')}}" rel="stylesheet">
<section id="services" class="services section">

  <!-- Section Title -->
  <div class="container section-title" data-aos="fade-up">
    <div><span>Check Our</span> <span class="description-title">Tutorials</span></div>
  </div><!-- End Section Title -->

  <div class="container">
    <div class="row gy-4">
      {% for service in services %}
    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="{{ loop.index * 100 }}">
        <div class="service-item position-relative">
            <div class="icon">
                <i class="bi bi-activity"></i>
            </div>
            <a href="{{ url_for('main.service_detail', service_name=service.name.replace(' ', '_')) }}" class="stretched-link">
                <h3>{{ service.name }}</h3>
            </a>
            <p>{{ service.description }}</p>
            <div class="progress mt-3">
                <div class="progress-bar" role="progressbar" style="width: {{ service.progress }}%;" aria-valuenow="{{ service.progress }}" aria-valuemin="0" aria-valuemax="100">{{ service.progress }}%</div>
            </div>
        </div>
    </div>
{% endfor %}

    </div>
  </div>

</section>
{% endblock content %}